### ISSUE TITLE
Exec Error

### ISSUE THREAD

**Issue by Picus13** [TryGhost/Ghost-Vagrant#102]
Hello,

I've a problem to mount Ghost on Vagrant on Mac OsX. 

When I enter 'vagrant up', my terminal return this error "Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long"

Ave you an idea to resolve this ?

Thx

**Comment by pekebyte** [comment]
I had the same issue, but I updated to vagrant 2.1.4 and it worked!.

**Comment by Picus13** [comment]
Okay, thank you. I will test it soon.
