### ISSUE TITLE
Error Installing Vagrant

### ISSUE THREAD

**Issue by kopepasah** [TryGhost/Ghost-Vagrant#53]
When I try to install the Vagrant for the first time, the Vagrant fails. I followed the directions on the `README.md`, and I apologize that I do not have any more information than [this log here](https://gist.github.com/kopepasah/f50860cf785903ac5804).

**Comment by ksr583** [comment]
Had this same issue.

**Comment by jaswilli** [comment]
This was a while back so I'm not sure anyone is still having this issue (or still concerned about it).  It does appear to be a permission/transient issue with node_modules.  It looks like the shared directory might be a Dropbox share?  It may be unrelated but it's a little suspicious...

Anyway, I'm going to close this but if someone can provie enough details that it can be reproduced I'm happy to look into it.
