### ISSUE TITLE
Error: grunt init returned 6 instead of one of [0]

### ISSUE THREAD

**Issue by jonblack** [TryGhost/Ghost-Vagrant#58]
I get the following output during `vagrant up`:

    Notice: /Stage[main]/Mysql/Mysql_database[ghost_test]/ensure: created
    Notice: /Stage[main]/Mysql/Mysql_user[ghost@localhost]/ensure: created
    Notice: /Stage[main]/Mysql/Mysql_database[ghost_dev]/ensure: created
    Notice: /Stage[main]/Mysql/Mysql_database[ghost_prod]/ensure: created
    Notice: Finished catalog run in 368.79 seconds
    
    
    Stderr from the command:
    
    stdin: is not a tty
    Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
    Error: grunt init returned 6 instead of one of [0]
    Error: /Stage[main]/Ghost/Exec[grunt init]/returns: change from notrun to 0 failed: grunt init returned 6 instead of one of [0]

I'm unsure if it's related but `http://local.tryghost.org/` gives a 502 bad gateway error.

**Comment by sebgie** [comment]
Hey,
this issue has been open for almost a year now. Ghost-Vagrant has changed significantly and I would like to ask you to try the new version. I'll close this issue for now and reopen if the problem still happens.
