### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by hoxoa** [TryGhost/Ghost-Vagrant#60]
I followed the guide in the readme, but got errors while doing `vagrant up`. 
Also I noticed that in this repo and in my clone after running the two `git submodule` steps, that `sqlite` isn't in the modules folder. 
Can you please check if everything is working for you.

Maybe this has to do with the change to ember-cli or so...  /cc @novaugust 

Thanks in advance

**Comment by novaugust** [comment]
Hey @hoxoa, we haven't made any real changes to vagrant in about half a year, so any folders that were there before should still be there. Changes from the ember-cli switchover wouldn't've affected sqlite in any way. Sorry to not be more helpful.
If you do figure something out, PRs would be more than welcome

**Comment by peterblazejewicz** [comment]
I had the same problem with `vagrant up` as it fails in `grunt init` part. I've tried updated `npm` module with added `sudo`, but that seems to be not the case.
If I perform a clean slate install via `git clone` of Ghost, the same `grunt init` task succeeds:
https://github.com/TryGhost/Ghost/issues/5107#issuecomment-89976706

**Comment by hoxoa** [comment]
@novaugust sorry for not being clear enough, the ember-cli part and the folder stuff were meant as two different things :). Haven't got it working, will write when I got it fixed, but otherwise waiting for @cwonrails rewrite.

**Comment by cwonrails** [comment]
@hoxoa @novaugust Just saw this - shall we take the rewrite discussion to a new issue or Slack?

**Comment by sebgie** [comment]
I try to clean up this repository. I'll close this issue since there have been some changes that probably solve above problem.
