### ISSUE TITLE
NFS does not work on Mac

### ISSUE THREAD

**Issue by hadifarnoud** [TryGhost/Ghost-Vagrant#62]
I have Vagrant 1.6.3 and OSX 10.10.1

it get stuck at default: Mounting NFS shared folders... and then gives the following error after a while:
```
The following SSH command responded with a non-zero exit status.                            
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 192.168.33.1:'/Users/hadifarnoud/Projects/Vagrant/ghost' /home/vagrant/code/Ghost

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: Connection timed out
```

**Comment by hadifarnoud** [comment]
I googled for a solution and tried so many of them. I'm not sure which one of these solved the issue but here it is the last two tries that solved the NFS issue:

I did `sudo ifconfig vboxnet0 down` and `sudo ifconfig vboxnet0 up`. and the same for vboxnet1 and vboxnet2.

I also had `192.168.33.21   kamva.dev` on my OSX /etc/hosts. Although its a different IP, I read somewhere commenting this would help. 

btw, why use NFS? isn't there any other solution?

**Comment by Ghosh** [comment]
@hadifarnoud Hey! How did you mange to fix this? I am having the exact same issue.

**Comment by cwonrails** [comment]
I actually agree regarding the sharing setup and etc/hosts modding; what solution(s) do you report?

**Comment by cwonrails** [comment]
Also what are your node and npm versions?

**Comment by Ghosh** [comment]
I had the same exact problem. I got around it by changing nfs to false in the Vagrantfile.

Would like to know a proper solution too.

**Comment by cwonrails** [comment]
@Ghosh Thanks for the info, very helpful! Are / were you primarily editing the Ghost code within or outside the box? Also, were you running stable or master?

**Comment by Ghosh** [comment]
I was developing a theme, so I was on master. And mostly I was editing the files from outside. It really shouldn't matter as Vagrant kind of syncs changes both ways.

**Comment by hadifarnoud** [comment]
I never got NFS to work @cwonrails

**Comment by cwonrails** [comment]
@Ghosh @hadifarnoud Thanks for the info + feedback; I'm going to work on debugging this over the next few days. Also, what Vagrant and Virtualbox versions are you working with right now? [Vagrant 1.7.3](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md) just added support for [Virtualbox 5.0](https://www.virtualbox.org/wiki/Downloads), which could affect the issues with sharing.

**Comment by Ghosh** [comment]
@cwonrails Im on Vagrant 1.6.5 and Virtualbox 4.3. Is it working for you after updating?

@hadifarnoud Maybe this issue could be reopened until a correct solution is found. What say?

**Comment by hadifarnoud** [comment]
@Ghosh I don't mind retrying this. I'm also on Virtualbox 4.x

**Comment by sjardim** [comment]
I manage to get it to work.
I my case, a message said that I got a conflict with another VM (scotch box). I destroy it and tried again. Now a new message said that I got a problem with my /etc/exports. So I deleted it and now it worked:
MAC
`sudo rm /etc/exports`
`sudo touch /etc/exports`

Note: We'll need to install node and npm to install Ghost. Documentation doesn't not cover it.

VM
`sudo apt-get update`
`sudo apt-get install nodejs`
`sudo apt-get install npm`

**Comment by sebgie** [comment]
Hey, this issue has been open for some time now. It seems like there is a suggested fix for the problem that has to do with conflicting configurations on the host system. I'll close this issue for now and reopen if the problem still happens.
