### ISSUE TITLE
Improve nginx SSL setup

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-Vagrant#64]
The no.1 thing I use Vagrant for, is testing SSL and the URL configs that you can't do without nginx. 

The keys are present on the box, but the `default` nginx config doesn't use them, which is fine. However it would be really nice to:

1) provide an easy way to switch to the SSL config
2) document what that is in the README

I think the `default` nginx config is kind of halfway to having an SSL config that can be uncommented, but I believe it's missing some stuff. The config file also has other bits and pieces in it which I think are unnecessary.

It would be better, I think, if it matched the [support](http://support.ghost.org/setup-ssl-self-hosted-ghost/) [docs](http://support.ghost.org/basic-nginx-config/).

**Comment by cwonrails** [comment]
Agreed. Should I get to work on it from the basis of my PR or from the current box?

**Comment by sebgie** [comment]
> The keys are present on the box, but the default nginx config doesn't use them, which is fine.

This [PR](https://github.com/sebgie/Ghost-Vagrant/commit/78d6bd9f09f2f59d0475b2e96e5dbbdd0e94d422) added the SSL config to nginx? The Ghost config doesn't use it by default so the Vagrant environment won't force you to use SSL.

Are you looking for something different or a special use case?

**Comment by ErisDS** [comment]
I don't know how, maybe because provisioning didn't completely properly - but the `default` file I had looked nothing like that. I've just freshly provisioned the new version according to the instructions and I can see the correct version now.

Closing this as it's already done :smiling_imp:
