### ISSUE TITLE
VM doesn't pick the changes when saving a file outside of the VM

### ISSUE THREAD

**Issue by lukaszklis** [TryGhost/Ghost-Vagrant#65]
Whenever I ssh into vagrant's machine and start grunt dev from there, open a file in vim inside the vm and save it, watch is triggered properly. Whenever I'm using a text editor/IDE outside of the VM and I try to save changes, watch doesn't seem to work anymore.

I've recorded two videos illustrating the issue:

- [Using editor inside of VM](https://dl.dropboxusercontent.com/u/97752/ghost-inside%20vm.mp4) (a MP4 file, ~11MB)
- [Using editor outside of VM](https://dl.dropboxusercontent.com/u/97752/ghost-outside%20vm.mp4) (a MP4 file, ~4MB)

It may be related to NFS.

**Comment by sebgie** [comment]
Hey, this issue has been open for some time now. Ghost-Vagrant has changed and I would like to ask you to try the new version. I'll close this issue for now and reopen if the problem still happens.
