### ISSUE TITLE
Automatic Vagrant Plugin Installation

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost-Vagrant#71]
I was wondering if we could make the installation process for users who don't have any experience using vagrant a bit easier (reduce the number of commands needed) by automatically installing the needed Vagrant plugins?

According to this [StackOverflow thread](http://stackoverflow.com/questions/19492738/demand-a-vagrant-plugin-within-the-vagrantfile) this isn't supported by default. But the thread points out a possible solution:

```
required_plugins = %w( vagrant-hostsupdater vagrant-someotherplugin )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end
```

@mike182uk: Since you added the plugins, what do you think about this approach?

**Comment by mike182uk** [comment]
Hey @sebgie,

Yeh i think this would be a good approach. Its probably something i should of done when i first introduced the plugins.

As for the code snippet, i don't think this is going to work as it is - by the time the code has been executed Vagrant has already bootstrapped all its plugin stuff, so despite the fact you have installed the plugins, Vagrant will not recognise them. This will mean you would have to run `vagrant up` a second time for Vagrant to run with the additional plugins.

Something like:

```ruby
missing_plugins = false
required_plugins = %w(vagrant-cachier vagrant-hostsupdater vagrant-librarian-puppet)

required_plugins.each do |plugin|
  if !Vagrant.has_plugin? plugin
    missing_plugins = true
    system "vagrant plugin install #{plugin}"
  end
end

if missing_plugins
  exec "vagrant #{ARGV.join(" ")}"
end
```

should work without having to run `vagrant up` a second time. This will install the required plugins using `system`, then if it did needed to install new plugins `vagrant up` is re-executed using `exec`. `exec` will replace the current process (`vagrant up` without the additional plugins) with `vagrant up` with the additional plugins.

**Comment by sebgie** [comment]
That sounds perfect. Would you like to send a PR?

**Comment by mike182uk** [comment]
Sure - https://github.com/TryGhost/Ghost-Vagrant/pull/74
