### ISSUE TITLE
Custom Configuration

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost-Vagrant#72]
With our current configuration it needs a bit of digging before someone who is not familiar with Vagrant is able to modify basic settings.

To make it easier to customize the configuration without having to understand how a Vagrantfile works, I would suggest to collect the following options in one place to make editing easier:

- VM hostname
- VM IP address
- VM memory
- Host directory that is mounted into `/home/vagrant/code/Ghost`

A short explanation what these values are used for would also help.

I see 2 options to make that work:
- add variables with comments at the beginning of our Vagrantfile
- add the option to use a separate config file (`config.yaml`) for these values

The values that are used in our current configuration seem to be sensible default values and should stay the same if the user doesn't change them manually.

Thoughts?

**Comment by mike182uk** [comment]
I would be in favour of using a separate config file. This would prevent the need to modify the Vagrantfile directly (which is under version control). I would say that the `config.yml` should be git ignored by default. The Vagrantfile will then source this in if it is present in the root directory. If a `config.yml` file is not present in the root directory, then one is generated automatically with the current sensible defaults.

**Comment by sebgie** [comment]
Yeah, adding the config to the `Vagrantfile` is probably not the best idea when it comes to version control :+1:.

Maybe have a `config.yml.example` that is cloned if no `config.yml` exists?
