### ISSUE TITLE
Adopt versioning process fully or drop versioning completely

### ISSUE THREAD

**Issue by mike182uk** [TryGhost/Ghost-Vagrant#81]
Hey,

Whilst i was updating the docs i came across the changelog section that contains version numbers for the changes that have been made. I can see that the version number is also included in the `motd` template.

The project does not seem to tag the versions or have any sort of release process around versioning so i'm not sure we are getting any benefit out of applying version numbers when we make a change. Its easy to forget to do this also when a change is made, so the documentation and referenced version number in the `motd` template soon become out of date.

I would like to propose one of the following:

a) drop applying version numbers and have a dated changelog instead
b) drop applying version numbers and drop the changelog - do we really need the changelog? can we not just see this information in the Git history if its really needed?
c) adopt a more formal release process and tag releases with the appropriate version number in Github

thoughts?

**Comment by sebgie** [comment]
Yeah, we have never tagged a version or done a release that would match with the version number from the changelog.

I would be in favour of switching to option b). Drop applying version numbers and use the commit history if needed. To make reading the commit history easier it would be great if we could also switch to commit messages that contain a short description of the changes? Probably follow the same format we use for Ghost (https://github.com/TryGhost/Ghost/wiki/Git-workflow#commit-messages):

```
Added something

closes/refs #<issue>
- added xyz
- removed abc
- updated zzz
```

**Comment by mike182uk** [comment]
:+1: I think this would be the best option also.
