### ISSUE TITLE
Error when running Vagrant up

### ISSUE THREAD

**Issue by littleneutrino** [TryGhost/Ghost-Vagrant#88]
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: ./Ghost

**Comment by mike182uk** [comment]
When following the steps in the readme, did you perform this one:

```
Clone the Ghost master repo with git clone git://github.com/Tryghost/Ghost.git (case matters!)
```

This should create the `Ghost` directory for you in the current directory (it needs to be in the same directory as the `Vagrantfile` unless you change the path in the `Vagrantfile`)

**Comment by stringsonfire** [comment]
Clarified readme in #89
