### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by stringsonfire** [TryGhost/Ghost-Vagrant#92]
I'm honestly not sure what to make of this. Running `npm install`, as in the readme:

```
vagrant@local:~$ cd code/Ghost
vagrant@local:~/code/Ghost$ npm install

> ghost@0.8.0 preinstall /home/vagrant/code/Ghost
> npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"

semver@5.1.0 node_modules/semver
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> typechecker@2.0.8 preinstall /home/vagrant/code/Ghost/node_modules/grunt-docker/node_modules/docker/node_modules/watchr/node_modules/bal-util/node_modules/typechecker
> node ./cyclic.js

npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
\
> jsonpath@0.2.3 postinstall /home/vagrant/code/Ghost/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})

> sqlite3@3.1.4 install /home/vagrant/code/Ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/home/vagrant/code/Ghost/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node" is installed via remote
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm ERR! EEXIST, open '/home/vagrant/.npm/cc7a7c07-nt-npm-lodash-4-12-0-package-tgz.lock'
File exists: /home/vagrant/.npm/cc7a7c07-nt-npm-lodash-4-12-0-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/vagrant/nvm/v0.10.38/bin/node" "/home/vagrant/nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /home/vagrant/code/Ghost
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/.npm/cc7a7c07-nt-npm-lodash-4-12-0-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
vagrant@local:~/code/Ghost$ npm start

> ghost@0.8.0 start /home/vagrant/code/Ghost
> node index

ERROR: Ghost is unable to start due to missing dependencies:
  Cannot find module 'cheerio'

Please run `npm install --production` and try starting Ghost again.
Help and documentation can be found at http://support.ghost.org.


npm ERR! ghost@0.8.0 start: `node index`
npm ERR! Exit status 233
npm ERR!
npm ERR! Failed at the ghost@0.8.0 start script.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/vagrant/nvm/v0.10.38/bin/node" "/home/vagrant/nvm/v0.10.38/bin/npm" "start"
npm ERR! cwd /home/vagrant/code/Ghost
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/code/Ghost/npm-debug.log
npm ERR! not ok code 0
vagrant@local:~/code/Ghost$ npm install --production
```

Running `npm install --production`, as in the readme on the Ghost repo:

```
vagrant@local:~/code/Ghost$ npm install --production

> ghost@0.8.0 preinstall /home/vagrant/code/Ghost
> npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"

npm WARN package.json passport@0.3.2 No README data
npm WARN package.json sqlite3@3.1.4 No README data
semver@5.1.0 node_modules/semver
npm WARN package.json passport@0.3.2 No README data
npm WARN package.json sqlite3@3.1.4 No README data
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
cheerio@0.20.0 node_modules/cheerio
├── entities@1.1.1
├── dom-serializer@0.1.0 (domelementtype@1.1.3)
├── css-select@1.2.0 (boolbase@1.0.0, css-what@2.1.0, nth-check@1.0.1, domutils@1.5.1)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, domutils@1.5.1, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.14)
├── jsdom@7.2.2 (acorn-globals@1.0.9, webidl-conversions@2.0.1, abab@1.0.3, xml-name-validator@2.0.1, sax@1.2.1, symbol-tree@3.1.4, cssom@0.3.1, nwmatcher@1.3.7, tough-cookie@2.2.2, whatwg-url-compat@0.6.5, parse5@1.5.1, acorn@2.7.0, escodegen@1.8.0, request@2.72.0, cssstyle@0.2.34)
└── lodash@4.12.0
```

Running `grunt init` as the next step, as on the readme:

```
vagrant@local:~/code/Ghost$ grunt init
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'top-gh-contribs'
Warning: Task "init" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by tobiasdalhof** [comment]
I had the same issue and fixed it by running `npm install` again.

**Comment by mike182uk** [comment]
I think this is related to https://github.com/npm/npm/issues/6309 which has been fixed in newer versions of npm. 

The actual error is:

```
npm ERR! EEXIST, open '/home/vagrant/.npm/cc7a7c07-nt-npm-lodash-4-12-0-package-tgz.lock'
File exists: /home/vagrant/.npm/cc7a7c07-nt-npm-lodash-4-12-0-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/vagrant/nvm/v0.10.38/bin/node" "/home/vagrant/nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /home/vagrant/code/Ghost
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/.npm/cc7a7c07-nt-npm-lodash-4-12-0-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

so `npm install` is failing mid install due to the following file existing: ` /home/vagrant/.npm/cc7a7c07-nt-npm-lodash-4-12-0-package-tgz.lock`

you could try manually removing this file: 

```
rm  /home/vagrant/.npm/cc7a7c07-nt-npm-lodash-4-12-0-package-tgz.lock
```

and then running `npm install` again. You may have to do this subsequent times if the same error keeps occuring with different files. once `npm install` completes without failure you can continue with the rest of the steps.

It may be worth us looking into upgrading to a more recent version of Node.js that Ghost supports.

**Comment by stringsonfire** [comment]
Tried again. Running `npm install` appears to have worked:

`vagrant@local:~/code/Ghost$ npm install

> ghost@0.8.0 preinstall /home/vagrant/code/Ghost
> npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"

npm WARN package.json passport@0.3.2 No README data
npm WARN package.json sqlite3@3.1.4 No README data
semver@5.1.0 node_modules/semver
npm WARN package.json passport@0.3.2 No README data
npm WARN package.json sqlite3@3.1.4 No README data`

But running `grunt init`:

`vagrant@local:~/code/Ghost$ grunt init
Running "update_submodules:default" (update_submodules) task

Running "shell:ember:init" (shell) task
Installing client dependencies...
npm WARN package.json ember-data-filter@1.13.0 No repository field.
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN engine portfinder@1.0.3: wanted: {"node":">= 0.12.0"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm ERR! EEXIST, open '/home/vagrant/.npm/9f379b11-ant-npm-mkdirp-0-5-1-package-tgz.lock'
File exists: /home/vagrant/.npm/9f379b11-ant-npm-mkdirp-0-5-1-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/vagrant/nvm/v0.10.38/bin/node" "/home/vagrant/nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /home/vagrant/code/Ghost/core/client
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/.npm/9f379b11-ant-npm-mkdirp-0-5-1-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
Warning: Command failed: npm WARN package.json ember-data-filter@1.13.0 No repository field.
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN engine portfinder@1.0.3: wanted: {"node":">= 0.12.0"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm ERR! EEXIST, open '/home/vagrant/.npm/9f379b11-ant-npm-mkdirp-0-5-1-package-tgz.lock'
File exists: /home/vagrant/.npm/9f379b11-ant-npm-mkdirp-0-5-1-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/vagrant/nvm/v0.10.38/bin/node" "/home/vagrant/nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /home/vagrant/code/Ghost/core/client
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/.npm/9f379b11-ant-npm-mkdirp-0-5-1-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
 Use --force to continue.

Aborted due to warnings.`

I can't `rm` it, as I get `No such file or directory`. I double checked the contents of the `.npm` folder, and this `.lock` file isn't there.

I tried again:

`vagrant@local:~/code/Ghost$ grunt init
Running "update_submodules:default" (update_submodules) task

Running "shell:ember:init" (shell) task
Installing client dependencies...
npm WARN package.json ember-data-filter@1.13.0 No repository field.
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm ERR! EEXIST, open '/home/vagrant/.npm/1a7f323d-roccoli-plugin-1-2-1-package-tgz.lock'
File exists: /home/vagrant/.npm/1a7f323d-roccoli-plugin-1-2-1-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/vagrant/nvm/v0.10.38/bin/node" "/home/vagrant/nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /home/vagrant/code/Ghost/core/client
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/.npm/1a7f323d-roccoli-plugin-1-2-1-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
Warning: Command failed: npm WARN package.json ember-data-filter@1.13.0 No repository field.
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm ERR! EEXIST, open '/home/vagrant/.npm/1a7f323d-roccoli-plugin-1-2-1-package-tgz.lock'
File exists: /home/vagrant/.npm/1a7f323d-roccoli-plugin-1-2-1-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/home/vagrant/nvm/v0.10.38/bin/node" "/home/vagrant/nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /home/vagrant/code/Ghost/core/client
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/.npm/1a7f323d-roccoli-plugin-1-2-1-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
 Use --force to continue.

Aborted due to warnings.`

But again, `No such file or directory`.

**Comment by bobthemac** [comment]
I too am having these issues I have tried in on two different machines and the exact same thing happens. My logs are identical to what is posted above and again there is no lock file. Although my lock file seems to be for a different package `4e1c944c-nt-npm-lodash-4-13-1-package-tgz.lock`. I have used this in the past and it worked fine could it be some issue relating to ghost 0.8 perhaps.

**Comment by ErisDS** [comment]
If you get an EEXIST error with a lock file whilst running `grunt init`, you can try:
`rm -rf core/client/node_modules`
`npm cache clear` 

and then run `grunt init` again.

If the error is consistent, you'll need to change the version of `npm` to a fixed version.

`grunt init` runs `npm install` inside the `core/client` subfolder. The error is coming from npm tripping itself up over its own lock files and is nothing to do with Ghost I'm afraid!

**Comment by stringsonfire** [comment]
Thanks @ErisDS, that fixed it. I've updated PR #90 to add this to the Readme.
