### ISSUE TITLE
Ember CLI requires higher version of node

### ISSUE THREAD

**Issue by tobiasdalhof** [TryGhost/Ghost-Vagrant#93]
after `grunt init` the following message appears:

Running "shell:ember:dev" (shell) task
DEPRECATION: Node v0.10.38 is no longer supported by Ember CLI. Please update to a more recent version of Node
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

**Comment by kevinansfield** [comment]
@tobiasdalhof: That notice is not strictly true, see discussion here https://github.com/ember-cli/ember-cli/issues/3329

**Comment by tobiasdalhof** [comment]
thanks @kevinansfield 
Sooo.. grunt continues loading after this message? I raged really hard during the installation of ghost-vagrant, so I did `vagrant-halt && vagrant destroy`.. should I try again?

**Comment by kevinansfield** [comment]
> Sooo.. grunt continues loading after this message?
Yes, it's just a warning not an error so everything continues fine.

**Comment by tobiasdalhof** [comment]
Thanks for the reply, bro. I close this issue for now.
